version: "3.9"
services:
  tts:
    image: ghcr.io/coqui-ai/tts
    ports:
      - "5002:5002"
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - COQUI_TOS_AGREED=1
      - TTS_MODEL="tts_models/en/ljspeech/tacotron2-DDC"
      - VOCODER_MODEL="vocoder_models/en/ljspeech/hifigan_v1"
    command: ["TTS/server/server.py", "--model_name", "tts_models/en/vctk/vits"]
    runtime: nvidia
    volumes:
      - ./tts:/root/.local/share
      - /etc/timezone:/etc/timezone:ro
    deploy:
      resources:
        reservations:
          devices:
            - count: all
              capabilities: [gpu]
