const assert = require('assert');
const fs = require('fs');

const html = fs.readFileSync('frontend/psychic/index.html', 'utf8');
const script = fs.readFileSync('frontend/psychic/psychic.js', 'utf8');
const styles = fs.readFileSync('frontend/psychic/styles.css', 'utf8');

assert(html.includes('id="graph-mode"'));
assert(html.includes('id="timeline-mode"'));
assert(html.includes('id="timeline-shell"'));
assert(html.includes('id="timeline-play"'));
assert(html.includes('id="timeline-pause"'));
assert(html.includes('id="timeline-zoom-in"'));
assert(html.includes('id="timeline-zoom-out"'));
assert(html.includes('id="timeline-zoom-reset"'));
assert(html.includes('id="timeline-scrub"'));
assert(html.includes('id="timeline-selection"'));
assert(html.includes('id="timeline-playhead"'));
assert(html.includes('id="present-panel"'));
assert(html.includes('id="present-media"'));
assert(html.includes('class="timeline-head"'));
assert(script.includes('const timelineModeStorageKey = "psychic.view.mode.v1";'));
assert(script.includes('const timelineRows = ['));
assert(script.includes('{ id: "images", label: "Images", kinds: ["Image", "FaceInstance"] }'));
assert(script.includes('{ id: "audio", label: "Audio Clips", kinds: ["AudioClip"] }'));
assert(script.includes('function setViewMode(mode, options = {})'));
assert(script.includes('function renderTimeline()'));
assert(script.includes('function timelineItems()'));
assert(script.includes('function timelineDurationMs(node)'));
assert(script.includes('function timelineClipElement(item)'));
assert(script.includes('function renderTimelineRuler()'));
assert(script.includes('function updateTimelinePlayhead()'));
assert(script.includes('function hydrateTimelineMedia(items)'));
assert(script.includes('let timelineFullExtent = null;'));
assert(script.includes('function zoomTimelineBy(factor)'));
assert(script.includes('function setTimelineWindow(min, max)'));
assert(script.includes('function resetTimelineZoom()'));
assert(script.includes('function startTimelineSelection(event)'));
assert(script.includes('function finishTimelineSelection(event)'));
assert(script.includes('function updateTimelineSelectionOverlay()'));
assert(script.includes('function playTimeline()'));
assert(script.includes('function pauseTimeline()'));
assert(script.includes('function renderPresentInstant()'));
assert(script.includes('function latestImageAtTimelineCursor()'));
assert(script.includes('function renderPresentImageFrame(imageNode, media)'));
assert(script.includes('function renderPresentSpeechOverlays(container, imageNode)'));
assert(script.includes('function visibleSpeechSegments(imageNode)'));
assert(script.includes('const wantedIds = new Set(segments.map((segment) => segment.node.id));'));
assert(script.includes('.filter((segment) => segment.start <= timelineCursor)'));
assert(script.includes('function imageTimelineWindow(imageNode)'));
assert(script.includes('function speechSegmentText(node)'));
assert(script.includes('el.className = "present-speech-segment";'));
assert(script.includes('el.classList.toggle("active", segment.start <= timelineCursor && segment.end >= timelineCursor);'));
assert(script.includes('const timelineImagePreloadCache = new Map();'));
assert(script.includes('function preloadTimelineImageNode(node)'));
assert(script.includes('function timelineImageSrcForNode(node)'));
assert(script.includes('function pruneTimelineImagePreloadCache(visibleIds)'));
assert(script.includes('.filter(timelineItemVisible);'));
assert(script.includes('visibleImageItems.forEach((item) => preloadTimelineImageNode(item.node));'));
assert(script.includes('timelineScrubEl.addEventListener("input"'));
assert(script.includes('timelinePlayEl.addEventListener("click", playTimeline);'));
assert(script.includes('timelinePauseEl.addEventListener("click", pauseTimeline);'));
assert(script.includes('timelineZoomInEl.addEventListener("click", () => zoomTimelineBy(0.5));'));
assert(script.includes('timelineBoardEl.addEventListener("pointerdown", startTimelineSelection);'));
assert(styles.includes('.view-toggle'));
assert(styles.includes('.timeline-shell'));
assert(styles.includes('.timeline-ruler'));
assert(styles.includes('.timeline-playback'));
assert(styles.includes('.timeline-zoom'));
assert(styles.includes('.timeline-selection'));
assert(styles.includes('.present-panel'));
assert(styles.includes('.present-media img'));
assert(styles.includes('.present-frame'));
assert(styles.includes('.present-speech-overlay'));
assert(styles.includes('display: inline;'));
assert(styles.includes('@keyframes present-speech-pop'));
assert(styles.includes('.present-speech-segment.active'));
assert(styles.includes('.timeline-clip-audio'));
assert(styles.includes('.timeline-playhead'));
assert(styles.includes('.timeline-head'));
console.log('psychic-timeline-mode ok');
