const assert = require('assert');
const fs = require('fs');

const html = fs.readFileSync('frontend/psychic/index.html', 'utf8');
const script = fs.readFileSync('frontend/psychic/psychic.js', 'utf8');
const styles = fs.readFileSync('frontend/psychic/styles.css', 'utf8');

assert(html.includes('id="graph-mode"'));
assert(html.includes('id="timeline-mode"'));
assert(html.includes('id="timeline-shell"'));
assert(html.includes('id="timeline-step-back"'));
assert(html.includes('id="timeline-play"'));
assert(html.includes('id="timeline-step-forward"'));
assert(html.includes('id="timeline-pause"'));
assert(html.includes('id="timeline-zoom-in"'));
assert(html.includes('id="timeline-zoom-out"'));
assert(html.includes('id="timeline-zoom-reset"'));
assert(html.includes('id="timeline-scrub"'));
assert(html.includes('id="timeline-filters"'));
assert(html.includes('id="timeline-selection"'));
assert(html.includes('id="timeline-playhead"'));
assert(html.includes('id="present-panel"'));
assert(html.includes('id="present-media"'));
assert(html.includes('class="timeline-head"'));
assert(script.includes('const timelineModeStorageKey = "psychic.view.mode.v1";'));
assert(script.includes('const timelineRowPriority = ['));
assert(script.includes('const timelineRowLabels = new Map(['));
assert(script.includes('function setViewMode(mode, options = {})'));
assert(script.includes('function renderTimeline()'));
assert(script.includes('function timelineItems()'));
assert(script.includes('function timelineRowsForItems(items)'));
assert(script.includes('function timelineRowId(kind)'));
assert(script.includes('function timelineRowLabel(kind)'));
assert(script.includes('function timelineRowSort(left, right)'));
assert(script.includes('function timelineDurationMs(node)'));
assert(script.includes('function speechSegmentDurationMs(props)'));
assert(script.includes('if (speechDuration !== null) return speechDuration;'));
assert(script.includes('function timelineRangeForNode(node)'));
assert(script.includes('function timelineStartMs(node)'));
assert(script.includes('function transcriptionTimelineRangeMs(node)'));
assert(script.includes('function transcriptionRelationshipRangeMs(node, fallbackStart)'));
assert(script.includes('function audioClipStartMs(node)'));
assert(script.includes('function audioClipDurationMs(node)'));
assert(script.includes('function audioClipRelationshipDurationMs(node)'));
assert(script.includes('function speechSegmentsForAudioClip(audioClipId)'));
assert(script.includes('function speechSegmentTimelineStartMs(node)'));
assert(script.includes('function speechSegmentAudioAnchors(node)'));
assert(script.includes('function speechSegmentAudioAnchorFromRelationship(nodeId, rel)'));
assert(script.includes('timestampProperty(props, "source_started_at")'));
assert(script.includes('timestampProperty(props, "source_ended_at")'));
assert(script.includes('timestampProperty(props, "captured_at")'));
assert(script.includes('const relationshipDuration = audioClipRelationshipDurationMs(node);'));
assert(script.includes('return audioStart === null ? null : audioStart + anchor.offsetMs;'));
assert(script.includes('const offsetMs = numericProperty(props, "clip_start_ms") ?? numericProperty(props, "start_ms");'));
assert(script.includes('const audioClipId = typeof props.audio_clip_id === "string" ? props.audio_clip_id : "";'));
assert(script.includes('function timelineClipElement(item)'));
assert(script.includes('function timelineClipWidthPercent(item, left = timelineFullPercent(item.start))'));
assert(script.includes('if (["AudioClip", "SpeechSegment", "Transcription"].includes(nodeKind(item.node))) return Math.max(width, 0);'));
assert(script.includes('function selectTimelineClip(item, event)'));
assert(script.includes('function jumpTimelineHeadToItem(item, event)'));
assert(script.includes('const timestamp = event ? timestampAtTimelineClientX(event.clientX) : item.start;'));
assert(script.includes('timelineCursor = Math.max(timelineFullExtent.min, Math.min(timestamp ?? item.start, timelineFullExtent.max));'));
assert(script.includes('function timelineClipClass(node)'));
assert(script.includes('function isTimelineImageNode(node)'));
assert(script.includes('function timelineImagePreviewElement(node, media = mediaForNode(node))'));
assert(script.includes('clip.append(timelineImagePreviewElement(item.node, media));'));
assert(script.includes('function timelineAudioWaveformElement(node, media = mediaForNode(node))'));
assert(script.includes('function audioWaveformLevels(props, media, bucketCount = 48)'));
assert(script.includes('function wavPcmS16Samples(bytes)'));
assert(script.includes('function placeholderAudioWaveformLevels(bucketCount = 32)'));
assert(script.includes('function timelineSensationIconLabel(node)'));
assert(script.includes('combobulation_summary: { icon: "💭", label: "Combobulation sensation" }'));
assert(script.includes('function renderTimelineRuler()'));
assert(script.includes('function updateTimelinePlayhead()'));
assert(script.includes('function hydrateTimelineMedia(items)'));
assert(script.includes('let timelineFullExtent = null;'));
assert(script.includes('let timelineZoomSpan = null;'));
assert(script.includes('function zoomTimelineBy(factor)'));
assert(script.includes('function setTimelineWindow(min, max)'));
assert(script.includes('function resetTimelineZoom()'));
assert(script.includes('function startTimelineSelection(event)'));
assert(script.includes('function finishTimelineSelection(event)'));
assert(script.includes('function updateTimelineSelectionOverlay()'));
assert(script.includes('function updateTimelineViewportFromScroll()'));
assert(script.includes('function scrollTimelineToWindow(min, max)'));
assert(script.includes('function timelineFullPercent(timestamp)'));
assert(script.includes('function playTimeline()'));
assert(script.includes('function pauseTimeline()'));
assert(script.includes('function stepTimelineFrame(direction)'));
assert(script.includes('function visibleTimelineFrameTimestamps()'));
assert(script.includes('function renderPresentInstant()'));
assert(script.includes('function latestImageAtTimelineCursor()'));
assert(script.includes('function renderPresentImageFrame(imageNode, media)'));
assert(script.includes('function renderPresentMovie(movie)'));
assert(script.includes('function loadMovieIndex(options = {})'));
assert(script.includes('function requestMovieForTimelineCursor()'));
assert(script.includes('fetch("/movie", {'));
assert(script.includes('function movieForTimelineCursor()'));
assert(script.includes('function scrubTextTrackCues(track)'));
assert(script.includes('function stripTranscriptionTimeTags(value)'));
assert(script.includes('if (nodeKind(node) === "SpeechSegment") return speechSegmentText(node);'));
assert(script.includes('stripTranscriptionTimeTags(String(props.text || props.transcript || props.summary || nodeLabel(node)))'));
assert(script.includes('const maxHeadMovieDurationMs = 180000;'));
assert(script.includes('const headMovieRequestDurationMs = 90000;'));
assert(script.includes('video.preload = timelinePlaying ? "auto" : "metadata";'));
assert(script.includes('track.kind = "captions";'));
assert(script.includes('function renderPresentSpeechOverlays(container, imageNode)'));
assert(script.includes('function visibleSpeechSegments(imageNode)'));
assert(script.includes('const wantedIds = new Set(segments.map((segment) => segment.node.id));'));
assert(script.includes('.filter((segment) => segment.start <= timelineCursor)'));
assert(script.includes('function imageTimelineWindow(imageNode)'));
assert(script.includes('function speechSegmentText(node)'));
assert(script.includes('el.className = "present-speech-segment";'));
assert(script.includes('el.classList.toggle("active", segment.start <= timelineCursor && segment.end >= timelineCursor);'));
assert(script.includes('return "Instance of a face";'));
assert(!script.includes('`face${index}`'));
assert(script.includes('const timelineImagePreloadCache = new Map();'));
assert(script.includes('function preloadTimelineImageNode(node)'));
assert(script.includes('function timelineImageSrcForNode(node)'));
assert(script.includes('function pruneTimelineImagePreloadCache(visibleIds)'));
assert(script.includes('.filter(timelineItemVisible);'));
assert(script.includes('const visibleMediaItems = items'));
assert(script.includes('visibleImageItems.forEach((item) => preloadTimelineImageNode(item.node));'));
assert(script.includes('const loadableImageItems = visibleImageItems'));
assert(script.includes('timelineScrubEl.addEventListener("input"'));
assert(script.includes('timelineStepBackEl.addEventListener("click", () => stepTimelineFrame(-1));'));
assert(script.includes('timelinePlayEl.addEventListener("click", playTimeline);'));
assert(script.includes('timelineStepForwardEl.addEventListener("click", () => stepTimelineFrame(1));'));
assert(script.includes('timelinePauseEl.addEventListener("click", pauseTimeline);'));
assert(script.includes('timelineZoomInEl.addEventListener("click", () => zoomTimelineBy(0.5));'));
assert(script.includes('timelineBoardEl.addEventListener("pointerdown", startTimelineSelection);'));
assert(script.includes('timelineBoardEl.addEventListener("scroll", handleTimelineScroll);'));
assert(styles.includes('.view-toggle'));
assert(styles.includes('.timeline-shell'));
assert(styles.includes('.timeline-filter-panel'));
assert(styles.includes('.timeline-ruler'));
assert(styles.includes('.timeline-playback'));
assert(styles.includes('.timeline-zoom'));
assert(styles.includes('.timeline-selection'));
assert(styles.includes('.present-panel'));
assert(styles.includes('.present-media img'));
assert(styles.includes('.present-frame'));
assert(styles.includes('.present-movie-frame'));
assert(styles.includes('.present-movie-frame video'));
assert(styles.includes('.present-speech-overlay'));
assert(styles.includes('display: inline;'));
assert(styles.includes('@keyframes present-speech-pop'));
assert(styles.includes('.present-speech-segment.active'));
assert(styles.includes('.timeline-clip-audio'));
assert(styles.includes('.timeline-clip .timeline-image-placeholder'));
assert(styles.includes('.timeline-clip-speech'));
assert(styles.includes('.timeline-clip-transcription'));
assert(styles.includes('min-width: 0;'));
assert(styles.includes('box-sizing: border-box;'));
assert(styles.includes('.timeline-waveform'));
assert(styles.includes('.timeline-clip-event'));
assert(styles.includes('.timeline-sensation-icon'));
assert(styles.includes('.timeline-playhead'));
assert(styles.includes('.timeline-head'));
console.log('psychic-timeline-mode ok');
