[package]
name = "pete"
version = "0.1.0"
edition = "2024"

[dependencies]
psyche = { path = "../psyche" }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
anyhow = "1"
async-trait = "0.1"
axum = { version = "0.8", features = ["macros", "json", "tokio"] }
tokio-stream = { version = "0.1", features = ["sync"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
clap = { version = "4", features = ["derive"] }

[dev-dependencies]
assert_cmd = "2"
