[package]
name = "pete"
version = "0.1.0"
edition = "2024"

[dependencies]
psyche = { path = "../psyche" }
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
anyhow = "1"
log = { version = "0.4.27", features = ["std"] }
