use crate::{fond::FondDuCoeur, genie::Genie, witness::WitnessAgent};
use voice::{ThinkMessage, VoiceAgent};

/// Maintains Pete's current stream of consciousness.
pub struct Psyche {
    /// The latest summary of experiences.
    pub here_and_now: String,
    fond: FondDuCoeur,
}

impl Psyche {
    /// Create a new blank psyche.
    pub fn new() -> Self {
        Self {
            here_and_now: String::new(),
            fond: FondDuCoeur::new(),
        }
    }

    /// Update internal state from the [`WitnessAgent`] and ask the
    /// [`VoiceAgent`] to narrate the result.
    pub async fn tick<V: VoiceAgent>(&mut self, witness: &WitnessAgent, voice: &V) -> ThinkMessage {
        if let Some(s) = witness.last().cloned() {
            let _ = self.fond.feel(s).await;
            if let Ok(sum) = self.fond.consult().await {
                self.here_and_now = sum;
            }
        }
        let content = voice.narrate(&self.here_and_now).await;
        ThinkMessage { content }
    }

    /// Retrieve the identity paragraph generated by [`FondDuCoeur`].
    pub fn fond_identity(&self) -> &str {
        self.fond.identity()
    }
}
