[package]
name = "psyche"
version = "0.1.0"
edition = "2024"

[dependencies]
lingproc = { path = "../lingproc" }
futures = "0.3"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "sync"] }
warp = { version = "0.3", features = ["websocket"] }
log = "0.4"
once_cell = "1"

[dev-dependencies]
async-trait = "0.1"
async-stream = "0.3"
anyhow = "1"
