[package]
name = "psyche"
version = "0.1.0"
edition = "2024"

[dependencies]
lingproc = { path = "../lingproc" }
futures = "0.3"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "sync"] }
log = { version = "0.4", features = ["std"] }
once_cell = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
chrono = { version = "0.4", features = ["std", "clock"] }

[dev-dependencies]
async-trait = "0.1"
async-stream = "0.3"
anyhow = "1"
