import { MessageType } from "./MessageType.ts";

export interface SocketMessage {
  type: MessageType;
  data: Blob | string | Record<string, unknown>;
  at?: string;
  thought?: boolean; // If the message was generated by the connection
}

export function isValidSocketMessage(
  message: unknown,
): message is SocketMessage {
  if (typeof message !== "object" || message === null) {
    return false;
  }
  if (!("type" in message) || !("data" in message)) {
    return false;
  }
  return true;
}
