[package]
name = "sensation-tester"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
clap = { version = "4", features = ["derive"] }
tokio-tungstenite = "0.20"
serde_json = "1"
futures-util = "0.3"
